application: field-promotion
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /lib
  static_dir: lib

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /record
  script: handlers.record_game.app
  login: required

- url: /view
  script: handlers.view_game.app
  login: required

- url: /search
  script: handlers.search.app
  login: required

- url: /admin
  script: handlers.admin.app
  login: admin

- url: /*
  script: handlers.front_page.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
